"""
questions.py - Complete question bank for all 3 difficulty levels.
Each level has 3+ unique questions per attack type = fully different every session.
Cyber-Attack Simulator & Defense Lab
"""

import random

# ══════════════════════════════════════════════════════════════════════════════
# PHISHING QUESTIONS
# Each entry: dict with email_data, clickable elements, correct_target, hint
# ══════════════════════════════════════════════════════════════════════════════

PHISHING_QUESTIONS = {

    "beginner": [
        {
            "id": "ph_b1",
            "title": "Fake PayPal Verification",
            "from_addr": "security@paypa1.com",
            "to_addr": "employee@company.com",
            "subject": "Urgent: Verify Your Account Now",
            "body_lines": [
                ("text",    "Dear Valued Customer,"),
                ("text",    ""),
                ("text",    "We detected unusual login activity on your account."),
                ("text",    "Click below to verify your identity immediately:"),
                ("text",    ""),
                ("link",    "http://paypa1-secure.evil-tk.com/verify",  "malicious_link"),
                ("text",    ""),
                ("text",    "Failure to verify will result in"),
                ("urgent",  "permanent account suspension.",            "urgency_text"),
                ("text",    ""),
                ("sender",  "-- PayPal Security Team",                  "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "Look at the URL carefully — 'paypa1' uses digit 1 instead of letter l. That is a fake domain.",
            "explanation": "The link 'paypa1-secure.evil-tk.com' is a lookalike domain. Legitimate PayPal only uses paypal.com.",
            "logs": "MAIL|Incoming from: security@paypa1.com|ALERT|Domain mismatch: paypa1.com vs paypal.com|FILTER|Spam score: 8.7/10 HIGH RISK|MAIL|Suspicious link detected in body|SYSTEM|DMARC verification FAILED",
        },
        {
            "id": "ph_b2",
            "title": "Fake Bank Alert",
            "from_addr": "alerts@nationaI-bank.com",
            "to_addr": "user@office.com",
            "subject": "Your Account Has Been Locked",
            "body_lines": [
                ("text",    "Dear Account Holder,"),
                ("text",    ""),
                ("text",    "Your online banking access has been locked"),
                ("text",    "due to 3 incorrect password attempts."),
                ("text",    ""),
                ("text",    "To unlock your account, visit:"),
                ("link",    "http://nationaI-bank.login-verify.net/unlock", "malicious_link"),
                ("text",    ""),
                ("urgent",  "You have 12 hours before your account is closed.", "urgency_text"),
                ("text",    ""),
                ("sender",  "-- National Bank Security",                "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "Check the sender domain carefully. 'nationaI' uses uppercase letter I instead of lowercase l.",
            "explanation": "The domain 'nationaI-bank.com' has a capital I instead of lowercase l — classic homograph attack.",
            "logs": "MAIL|From: alerts@nationaI-bank.com|ALERT|Homograph domain attack detected|FILTER|Typosquatting pattern found|MAIL|External link to login-verify.net|SYSTEM|SPF record mismatch",
        },
        {
            "id": "ph_b3",
            "title": "Fake IT Support",
            "from_addr": "it-support@company-helpdesk.net",
            "to_addr": "john.doe@company.com",
            "subject": "Password Expiry Notice",
            "body_lines": [
                ("text",    "Hi John,"),
                ("text",    ""),
                ("text",    "Your company password expires in 24 hours."),
                ("text",    "Please reset it immediately using the link below:"),
                ("text",    ""),
                ("link",    "http://company-helpdesk.net/reset?token=xK9mP2", "malicious_link"),
                ("text",    ""),
                ("text",    "Contact us if you have questions."),
                ("sender",  "-- IT Support Team",                       "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "Legitimate IT departments use your company's own domain, not external sites like 'company-helpdesk.net'.",
            "explanation": "The reset link goes to an external domain 'company-helpdesk.net' — not the real company server.",
            "logs": "MAIL|From: it-support@company-helpdesk.net|ALERT|External domain impersonating IT dept|FILTER|Reset token in URL is suspicious|SYSTEM|Not from internal mail server",
        },
    ],

    "intermediate": [
        {
            "id": "ph_i1",
            "title": "Spear Phish — CEO Fraud",
            "from_addr": "ceo.johnson@company-corp.co",
            "to_addr": "accounts@company.com",
            "subject": "Urgent Wire Transfer Required",
            "body_lines": [
                ("text",    "Hi Sarah,"),
                ("text",    ""),
                ("text",    "I need you to process an urgent wire transfer of $45,000"),
                ("text",    "for a confidential acquisition deal closing today."),
                ("text",    ""),
                ("text",    "Transfer details are in the secure document:"),
                ("link",    "http://docs-company-secure.ru/transfer-details.pdf", "malicious_link"),
                ("text",    ""),
                ("urgent",  "This is time-sensitive. Do not discuss with anyone.", "urgency_text"),
                ("text",    ""),
                ("sender",  "-- Robert Johnson, CEO",                   "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "The CEO email uses 'company-corp.co' not 'company.com'. Also the .ru document link is a red flag.",
            "explanation": "CEO fraud (BEC) uses a near-identical domain. The .ru document link confirms malicious intent.",
            "logs": "MAIL|From: ceo.johnson@company-corp.co|ALERT|Domain mismatch — company-corp.co vs company.com|ALERT|Russian (.ru) document server detected|FILTER|BEC pattern: urgent wire transfer|SYSTEM|CEO email impersonation flagged",
        },
        {
            "id": "ph_i2",
            "title": "Fake Microsoft 365 Login",
            "from_addr": "no-reply@micros0ft-365.com",
            "to_addr": "employee@firm.com",
            "subject": "Action Required: Sign-in Attempt Blocked",
            "body_lines": [
                ("text",    "Microsoft Account Security"),
                ("text",    ""),
                ("text",    "A sign-in from an unrecognized device was blocked."),
                ("text",    "Location: Minsk, Belarus — 04:13 AM"),
                ("text",    ""),
                ("text",    "If this was not you, secure your account now:"),
                ("link",    "https://micros0ft-365.com/secure-login?ref=blocked", "malicious_link"),
                ("text",    ""),
                ("urgent",  "Ignore this if you recognise this sign-in.",         "urgency_text"),
                ("sender",  "-- Microsoft Account Team",               "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "Microsoft uses microsoft.com only. 'micros0ft-365.com' uses zero instead of letter o.",
            "explanation": "'micros0ft-365.com' is a homoglyph attack — digit 0 replaces letter o. Real Microsoft never does this.",
            "logs": "MAIL|From: no-reply@micros0ft-365.com|ALERT|Homoglyph: 0 (zero) instead of o|FILTER|Fake Microsoft domain confirmed|MAIL|HTTPS does not equal legitimacy|SYSTEM|Phishing database match found",
        },
        {
            "id": "ph_i3",
            "title": "Fake HR Document",
            "from_addr": "hr.department@company-hr-portal.com",
            "to_addr": "staff@company.com",
            "subject": "Updated Employment Contract — Please Review",
            "body_lines": [
                ("text",    "Dear Team Member,"),
                ("text",    ""),
                ("text",    "Please review and sign your updated employment contract"),
                ("text",    "before the end of the week."),
                ("text",    ""),
                ("link",    "http://company-hr-portal.com/contracts/sign?id=8821", "malicious_link"),
                ("text",    ""),
                ("text",    "Contact HR if you have concerns."),
                ("urgent",  "Unsigned contracts will be escalated to management.", "urgency_text"),
                ("sender",  "-- Human Resources Department",            "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "HR portals should be on your company's own domain, not 'company-hr-portal.com' (a separate site).",
            "explanation": "The link goes to 'company-hr-portal.com' — a completely separate domain designed to harvest credentials.",
            "logs": "MAIL|From: hr.department@company-hr-portal.com|ALERT|External HR portal not on company domain|FILTER|Credential harvesting pattern detected|SYSTEM|Not sent from company mail server",
        },
    ],

    "expert": [
        {
            "id": "ph_e1",
            "title": "Advanced Supply Chain Attack",
            "from_addr": "invoices@trusted-vendor.support",
            "to_addr": "finance@targetcorp.com",
            "subject": "Invoice #INV-2026-4821 — Payment Overdue",
            "body_lines": [
                ("text",    "Dear Finance Team,"),
                ("text",    ""),
                ("text",    "Our records show Invoice #INV-2026-4821 ($12,340)"),
                ("text",    "remains unpaid after 30 days."),
                ("text",    ""),
                ("text",    "Please process payment or log into our portal:"),
                ("link",    "https://trusted-vendor.support/portal/inv-4821", "malicious_link"),
                ("text",    ""),
                ("text",    "Banking details have changed — updated details inside."),
                ("urgent",  "Late fees of 5% apply after 48 hours.",    "urgency_text"),
                ("sender",  "-- Accounts Receivable, Trusted Vendor Ltd", "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "'.support' TLD is often abused. The domain 'trusted-vendor.support' is different from the real vendor site. Banking details change notice is a major red flag.",
            "explanation": "Vendor impersonation with changed banking details is a BEC variant. The .support TLD and changed bank info are critical red flags.",
            "logs": "MAIL|From: invoices@trusted-vendor.support|ALERT|Non-standard TLD .support flagged|ALERT|Banking details change — high risk indicator|FILTER|Invoice fraud BEC pattern detected|SYSTEM|Domain registered 3 days ago",
        },
        {
            "id": "ph_e2",
            "title": "OAuth Consent Phishing",
            "from_addr": "noreply@googleapps-workspace.com",
            "to_addr": "developer@startup.io",
            "subject": "A third-party app is requesting access",
            "body_lines": [
                ("text",    "Google Workspace Security"),
                ("text",    ""),
                ("text",    "The app 'DevTools Pro' is requesting permission to:"),
                ("text",    "  - Read all your emails"),
                ("text",    "  - Access Google Drive files"),
                ("text",    "  - Manage your contacts"),
                ("text",    ""),
                ("link",    "https://googleapps-workspace.com/oauth/authorize?app=devtools", "malicious_link"),
                ("text",    ""),
                ("urgent",  "Deny access within 1 hour or permissions will be granted.", "urgency_text"),
                ("sender",  "-- Google Security",                       "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "Google OAuth only happens at accounts.google.com — never at 'googleapps-workspace.com' (a fake domain).",
            "explanation": "OAuth phishing tricks users into granting app permissions via fake consent pages. Google uses accounts.google.com only.",
            "logs": "MAIL|From: noreply@googleapps-workspace.com|ALERT|Fake OAuth consent page detected|ALERT|Not from google.com or accounts.google.com|FILTER|Consent phishing attack pattern|SYSTEM|Domain googleapps-workspace.com is not Google",
        },
        {
            "id": "ph_e3",
            "title": "Multi-Stage Callback Phishing",
            "from_addr": "support@adobe-creative.help",
            "to_addr": "designer@agency.com",
            "subject": "Your Creative Cloud subscription has a billing issue",
            "body_lines": [
                ("text",    "Adobe Creative Cloud"),
                ("text",    ""),
                ("text",    "We could not process your payment for Creative Cloud."),
                ("text",    "Your subscription will pause in 24 hours."),
                ("text",    ""),
                ("text",    "Call our billing team to resolve this:"),
                ("link",    "https://adobe-creative.help/billing/issue?ref=CC2026", "malicious_link"),
                ("text",    "Or call:"),
                ("urgent",  "+1-888-ADOBE-FAKE (Toll Free)",            "urgency_text"),
                ("sender",  "-- Adobe Customer Support",                "sender_name"),
            ],
            "correct": "malicious_link",
            "hint": "Adobe uses adobe.com only. 'adobe-creative.help' is a fake domain. The phone number combined with a link is a multi-stage vishing+phishing attack.",
            "explanation": "This combines a fake link AND a vishing phone number — a multi-stage attack. Adobe.com is the only legitimate domain.",
            "logs": "MAIL|From: support@adobe-creative.help|ALERT|Fake domain: adobe-creative.help not adobe.com|ALERT|Phone number phishing (vishing) component detected|FILTER|Multi-stage phishing pattern|SYSTEM|Domain registered recently — not Adobe",
        },
    ],
}

# ══════════════════════════════════════════════════════════════════════════════
# BRUTE FORCE QUESTIONS
# Each entry: log entries shown + the attacker IP to block
# ══════════════════════════════════════════════════════════════════════════════

BRUTEFORCE_QUESTIONS = {

    "beginner": [
        {
            "id": "bf_b1",
            "title": "SSH Login Attack",
            "description": "Multiple SSH login attempts detected on port 22. Type the attacking IP and click BLOCK.",
            "entries": [
                ("10.0.0.12",     "1 failed attempt",               False),
                ("192.168.1.5",   "2 failed attempts",              False),
                ("203.0.113.99",  "847 failed attempts — ATTACKER!", True),
                ("10.0.0.55",     "1 failed attempt",               False),
            ],
            "attacker_ip": "203.0.113.99",
            "hint": "The attacker always has hundreds of failed attempts. Normal users fail only 1-3 times.",
            "explanation": "203.0.113.99 made 847 attempts in 60 seconds — a clear automated brute force. Block immediately.",
            "logs": "AUTH|10.0.0.12 Login OK (1 attempt)|AUTH|192.168.1.5 failed (2 attempts)|ALERT|203.0.113.99 — 847 failed in 60s!|AUTH|10.0.0.55 Login OK|SYSTEM|Rate limit triggered on 203.0.113.99",
        },
        {
            "id": "bf_b2",
            "title": "FTP Brute Force",
            "description": "Repeated FTP login failures on port 21. Find and block the attacker IP.",
            "entries": [
                ("172.16.0.10",   "1 failed attempt",               False),
                ("10.10.0.3",     "3 failed attempts",              False),
                ("185.220.101.9", "512 failed attempts — ATTACKER!", True),
                ("192.168.0.20",  "2 failed attempts",              False),
            ],
            "attacker_ip": "185.220.101.9",
            "hint": "512 failed FTP logins in a short window means automated password spraying. One IP stands out clearly.",
            "explanation": "185.220.101.9 is a known Tor exit node used for automated attacks. 512 attempts confirms brute force.",
            "logs": "FTP|172.16.0.10 Login OK|FTP|10.10.0.3 failed (3 attempts)|ALERT|185.220.101.9 — 512 failed FTP logins!|FTP|192.168.0.20 failed (2 attempts)|SYSTEM|FTP brute force pattern detected",
        },
        {
            "id": "bf_b3",
            "title": "Web Panel Attack",
            "description": "Admin login panel under attack. Multiple IPs attempting access. Block the main attacker.",
            "entries": [
                ("10.0.1.5",      "1 failed attempt",               False),
                ("77.88.55.60",   "689 failed attempts — ATTACKER!", True),
                ("192.168.2.1",   "4 failed attempts",              False),
                ("10.0.1.22",     "Login OK (1 attempt)",           False),
            ],
            "attacker_ip": "77.88.55.60",
            "hint": "689 failed attempts is far above normal. Any user making hundreds of attempts is attacking, not forgetting their password.",
            "explanation": "77.88.55.60 with 689 failed attempts is dictionary-attacking the admin panel. Block this IP immediately.",
            "logs": "WEB|10.0.1.5 failed (1 attempt)|ALERT|77.88.55.60 — 689 failed admin logins!|WEB|192.168.2.1 failed (4 attempts)|WEB|10.0.1.22 Login OK|SYSTEM|Admin panel brute force alert",
        },
    ],